# Generated by Django 4.2.3 on 2023-09-03 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0006_alter_opportunity_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
