# Generated by Django 4.2.3 on 2023-09-03 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0007_alter_opportunity_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='role',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
