# Generated by Django 4.2.3 on 2023-09-03 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0005_alter_opportunity_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='batch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
